elasticsearch:
    image: elasticsearch
    ports:
        - 9200:9200

elasticsearch2:
    image: elasticsearch:2
    ports:
        - 9200:9200

kibana:
    image: kibana
    links:
        - elasticsearch
    ports:
        - 5601:5601
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
