elasticsearch:
    image: elasticsearch:2
    command: elasticsearch -Des.network.bind_host=0.0.0.0
    ports:
        - 9200:9200
        - 9300:9300
    # volumes:
    #     - ${PWD}/esdata:/usr/share/elasticsearch/data

kibana:
    image: kibana:4.2
    links:
        - elasticsearch
    ports:
        - 5601:5601
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200

gelk:
    image: bitergia/gelk
