redis:
    image: redis

mariadbdata:
    image: mariadb:10.0
    volumes:
        - /var/lib/mysql
    restart: no
    command: /bin/echo "Data-only container for mariadb."

mariadb:
    image: mariadb:10.0
    volumes_from:
        - mariadbdata
    expose:
        - "3306"
    environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    # command: --verbose

elasticsearch:
    image: elasticsearch:2
    command: elasticsearch -Des.network.bind_host=0.0.0.0
    ports:
        - 9200:9200
        - 9300:9300
    volumes:
        - ~/Docker/data/elasticsearch/:/usr/share/elasticsearch/data

nginx:
    image: nginx
    links:
        - gelk
    ports:
        - 9181:9181
    volumes:
        - ~/devel/GrimoireELK/docker/compose/rq-dash-nginx.conf:/etc/nginx/nginx.conf:ro
        - ~/devel/GrimoireELK/docker/compose/rq-dash-password:/etc/nginx/rq-dash-password:ro

gelk:
    image: bitergia/gelk
    links:
        - elasticsearch
        - redis
        - mariadb
    # ports:
    #     - 9181:9181
    expose:
        - "9181"
    volumes:
        - ~/devel/GrimoireELK:/home/bitergia/GrimoireELK
        - ~/devel/perceval:/home/bitergia/perceval
